/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_GestionUtilisateur (void);
GtkWidget* create_Identification (void);
GtkWidget* create_Gestion_des_observateurs (void);
GtkWidget* create_Accueil_Admin (void);
GtkWidget* create_Accueil_Agent_Bureau (void);
GtkWidget* create_Accueil_Electeur (void);
GtkWidget* create_Accueil_Obs (void);
GtkWidget* create_Statistique (void);
GtkWidget* create_GestionBV (void);
GtkWidget* create_GestionElection (void);
GtkWidget* create_GestionLstElect (void);
GtkWidget* create_Vote (void);
GtkWidget* create_reclamation (void);
GtkWidget* create_colorselectiondialog1 (void);
GtkWidget* create_filechooserdialog1 (void);
GtkWidget* create_inputdialog1 (void);
GtkWidget* create_menu1 (void);
GtkWidget* create_inputdialog2 (void);
