/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *GestionUtilisateur;
  GtkWidget *Identification;
  GtkWidget *Gestion_des_observateurs;
  GtkWidget *Accueil_Admin;
  GtkWidget *Accueil_Agent_Bureau;
  GtkWidget *Accueil_Electeur;
  GtkWidget *Accueil_Obs;
  GtkWidget *Statistique;
  GtkWidget *GestionBV;
  GtkWidget *GestionElection;
  GtkWidget *GestionLstElect;
  GtkWidget *Vote;
  GtkWidget *reclamation;
  GtkWidget *colorselectiondialog1;
  GtkWidget *filechooserdialog1;
  GtkWidget *inputdialog1;
  GtkWidget *inputdialog2;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  GestionUtilisateur = create_GestionUtilisateur ();
  gtk_widget_show (GestionUtilisateur);
  Identification = create_Identification ();
  gtk_widget_show (Identification);
  Gestion_des_observateurs = create_Gestion_des_observateurs ();
  gtk_widget_show (Gestion_des_observateurs);
  Accueil_Admin = create_Accueil_Admin ();
  gtk_widget_show (Accueil_Admin);
  Accueil_Agent_Bureau = create_Accueil_Agent_Bureau ();
  gtk_widget_show (Accueil_Agent_Bureau);
  Accueil_Electeur = create_Accueil_Electeur ();
  gtk_widget_show (Accueil_Electeur);
  Accueil_Obs = create_Accueil_Obs ();
  gtk_widget_show (Accueil_Obs);
  Statistique = create_Statistique ();
  gtk_widget_show (Statistique);
  GestionBV = create_GestionBV ();
  gtk_widget_show (GestionBV);
  GestionElection = create_GestionElection ();
  gtk_widget_show (GestionElection);
  GestionLstElect = create_GestionLstElect ();
  gtk_widget_show (GestionLstElect);
  Vote = create_Vote ();
  gtk_widget_show (Vote);
  reclamation = create_reclamation ();
  gtk_widget_show (reclamation);
  colorselectiondialog1 = create_colorselectiondialog1 ();
  gtk_widget_show (colorselectiondialog1);
  filechooserdialog1 = create_filechooserdialog1 ();
  gtk_widget_show (filechooserdialog1);
  inputdialog1 = create_inputdialog1 ();
  gtk_widget_show (inputdialog1);
  inputdialog2 = create_inputdialog2 ();
  gtk_widget_show (inputdialog2);

  gtk_main ();
  return 0;
}

